version: "3"
services:
  mysql:
    image: mysql:8.0.19
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
    - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nest_blog
      - MYSQL_ROOT_PASSWORD='root'
    ports:
      - 3306:3306
    networks:
      - private
  redis:
    image: redis
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    ports:
      - 6379:6379
    networks:
      - private
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - private
  nest-blog:
    image: yuukisakura/nest-blog:latest
    build:
      context: .
    ports:
      - 3000:3000
      - 4000:4000
    depends_on:
      - mysql
      - redis
      - es
    networks:
      - private
      - public
  nginx:
    image: nginx:stable-alpine
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.log:/var/log/nginx
    networks:
      - private
      - public
volumes:
  db-data:
  es-data:
  redis-data:
networks:
  public:
  private: